# Generated by Django 3.0.7 on 2020-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.FileField(default='', upload_to='pkart/images', verbose_name='Product image')),
                ('product_description', models.CharField(max_length=400)),
                ('product_price', models.CharField(max_length=10)),
            ],
        ),
    ]
